export const PROFILE_TYPES = [
  {
    value: 'manufacturer',
    label: 'Fabricant / Artisan',
    description: 'Vous produisez ou fabriquez des biens',
    icon: 'Hammer',
    iconBg: 'bg-orange-50 border-orange-200',
    iconColor: 'text-orange-500',
  },
  {
    value: 'reseller',
    label: 'Revendeur',
    description: 'Vous achetez et revendez des produits',
    icon: 'ShoppingBag',
    iconBg: 'bg-blue-50 border-blue-200',
    iconColor: 'text-blue-500',
  },
  {
    value: 'wholesaler',
    label: 'Grossiste / Semi-grossiste',
    description: 'Vous vendez en grande quantité',
    icon: 'Warehouse',
    iconBg: 'bg-emerald-50 border-emerald-200',
    iconColor: 'text-emerald-500',
  },
  {
    value: 'service_provider',
    label: 'Prestataire de services',
    description: 'Vous offrez des services aux clients',
    icon: 'BriefcaseBusiness',
    iconBg: 'bg-violet-50 border-violet-200',
    iconColor: 'text-violet-500',
  },
]

export const PLANS = [
  {
    value: 'demarrage',
    name: 'Démarrage',
    price: 'Gratuit',
    period: 'pour toujours',
    description: 'Pour commencer votre aventure digitale',
    color: 'from-zinc-600 to-zinc-500',
    popular: false,
    features: [
      '2 utilisateurs',
      '50 produits',
      '1 GB stockage',
      'Rapports basiques',
      'Support communautaire',
    ],
  },
  {
    value: 'pro',
    name: 'Pro',
    price: '15 000',
    period: 'FCFA / mois',
    description: 'Pour les entreprises en croissance',
    color: 'from-indigo-600 to-violet-600',
    popular: true,
    features: [
      '10 utilisateurs',
      '500 produits',
      '10 GB stockage',
      'Rapports avancés',
      'Support prioritaire',
      'API accès',
    ],
  },
  {
    value: 'business',
    name: 'Business',
    price: '45 000',
    period: 'FCFA / mois',
    description: 'Pour les entreprises établies',
    color: 'from-violet-600 to-purple-600',
    popular: false,
    features: [
      '50 utilisateurs',
      '5 000 produits',
      '50 GB stockage',
      'Analytics complets',
      'Support dédié',
      'Intégrations avancées',
      'Multi-devises',
    ],
  },
  {
    value: 'entreprise',
    name: 'Entreprise',
    price: 'Sur mesure',
    period: 'contactez-nous',
    description: 'Pour les grandes organisations',
    color: 'from-amber-500 to-orange-500',
    popular: false,
    features: [
      'Utilisateurs illimités',
      'Produits illimités',
      '500 GB stockage',
      'Tout Business +',
      'Account manager dédié',
      'SLA garanti',
      'Déploiement privé',
    ],
  },
]
